<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE salmentak [
<!ELEMENT salmentak (produktua) >
<!ELEMENT produktua (idProducto, izena, kopurua, pisua, prezioa, noizAteraDa, idLangilea, idDenda)>
<!ELEMENT idProducto (#PCDATA)>
<!ELEMENT izena (#PCDATA)>
<!ELEMENT kopurua (#PCDATA)>
<!ELEMENT pisua (#PCDATA)>
<!ELEMENT prezioa (#PCDATA)>
<!ELEMENT noizAteraDa (#PCDATA)>
<!ELEMENT idLangilea (#PCDATA)>
<!ELEMENT idDenda (#PCDATA)>
]>




<salmentak>
		<produktua>
			<idProducto>005</idProducto>
			<izena>Ogia</izena>
			<kopurua>5</kopurua>
			<pisua>2</pisua>
			<prezioa>10</prezioa>
			<noizAteraDa>2023/01/11</noizAteraDa>
			<idLangilea>IGOR001</idLangilea>
			<idDenda>001</idDenda>
		</produktua>
</salmentak>